# Generated by Django 5.0.4 on 2024-05-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='CONTACTNUMBER',
            new_name='CONTACTPHONE',
        ),
    ]
