# Generated by Django 5.0.4 on 2024-05-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_rename_contactnumber_contactdb_contactphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGISTERNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('REGISTEREMAIL', models.EmailField(blank=True, max_length=100, null=True)),
                ('REGISTERPASSWORD', models.CharField(blank=True, max_length=100, null=True)),
                ('REGISTERCONFIRMPASSWORD', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
