# Generated by Django 5.0.4 on 2024-06-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0004_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BILLINGNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('BILLINGEMAIL', models.EmailField(blank=True, max_length=100, null=True)),
                ('BILLINGADDRESS', models.CharField(blank=True, max_length=100, null=True)),
                ('BILLINGPHONE', models.IntegerField(blank=True, null=True)),
                ('BILLINGPRICE', models.IntegerField(blank=True, null=True)),
                ('BILLINGMESSAGE', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
