# Generated by Django 5.0.4 on 2024-06-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0005_billingdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Billingdb',
            new_name='Orderdb',
        ),
    ]
